name: reflectable_flutter
description: A minimal example using reflectable with Flutter.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  reflectable: any
  build_runner: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
