name: reflectable_flutter
description: A minimal example using reflectable with Flutter.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  reflectable:
    git:
      url: git://github.com/dart-lang/reflectable.git
      ref: version_fix_feb19
  build_runner: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
